### ISSUE TITLE
[BUG] kotlin.UninitializedPropertyAccessException: lateinit property collectionJob has not been initialized

### ISSUE THREAD

**Issue by lcdsmao** [dropbox/Store#120]
**Describe the bug**

When we run the instrumented test in Firebase Test Lab, sometimes App will crash due to the following exception:
>kotlin.UninitializedPropertyAccessException: lateinit property collectionJob has not been initialized
    at com.dropbox.flow.multicast.SharedFlowProducer.cancel(SharedFlowProducer.kt:93)
    at com.dropbox.flow.multicast.ChannelManager$Actor.onClosed(ChannelManager.kt:177)
    at com.dropbox.flow.multicast.StoreRealActor.doClose(StoreRealActor.kt:62)
    at com.dropbox.flow.multicast.StoreRealActor.access$doClose(StoreRealActor.kt:32)
    at com.dropbox.flow.multicast.StoreRealActor$1.invokeSuspend(StoreRealActor.kt:54)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)

**To Reproduce**
Not sure how to reproduce it.😥

**Smartphone (please complete the following information):**
 - Store Version [e.g. 4.0.0-alpha02]

**Comment by yigit** [comment]
no worries, problems seems obvious, I'll try to create a test to reproduce.
Thanks!

**Comment by kemalatli** [comment]
Hi, I have come across this in 4.0.0-alpha03. Can we expect this fix in the next release or is it already included? As mentioned, this really is hard to reproduce.

**Comment by ychescale9** [comment]
It's fixed in the latest snapshot build: `4.0.0-SNAPSHOT` but not "released" yet.

**Comment by eyalgu** [comment]
lets give  #130 a change to get merged in and release alpha4

**Comment by auras** [comment]
Cam we get a release with this, please?

**Comment by OlivierHartmann** [comment]
Hey,
I just got the same error. Can you at least re-open the ticket please ?
