### ISSUE TITLE
Upgrade to Kotlin 1.4

### ISSUE THREAD

**Issue by digitalbuddha** [dropbox/Store#191]
We had some issues with duration apis. Let's get updated to Kotlin 1.4

**Comment by romansl** [comment]
For example:
```
java.lang.NoSuchMethodError: No virtual method getINFINITE()D in class Lkotlin/time/Duration$Companion; or its super classes
        at com.dropbox.android.external.store4.MemoryPolicy.<clinit>(MemoryPolicy.kt:70)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:24)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:90)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:87)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:64)
```

**Comment by digitalbuddha** [comment]
Working on a release today

**Comment by NahroTo** [comment]
We can close this issue, now [4.0.0-alpha-07](https://github.com/dropbox/Store/releases/tag/4.0.0-alpha07) is out.

**Comment by SteinerOk** [comment]
@NahroTo but it still unavailable in MavenCentral :(

**Comment by NahroTo** [comment]
@SteinerOk Yeah unfortunately. It's related to issue #215.
