### ISSUE TITLE
[BUG] No static method getHours when using Store

### ISSUE THREAD

**Issue by user-fal** [dropbox/Store#266]
Hi team,

Thanks for this great library.
I am using Kotlin 1.4.31 with Store 4.0.0 and Kotlin Coroutine 1.4.1.
Unfortunately, my app crashes when I launch my app just for a simple usecase: Loading some countries.
Error stacktrace is related to Duration class in Kotlin.

Part of my code:

```
val sourceOfTruth = SourceOfTruth.of(reader = { countryDao.loadCountries() },
            writer = { _: String, input: List<CountryDomain> ->
                countryDao.insertAll(input.toBean())
            },
            deleteAll = { countryDao.deleteAll() })

        val store = StoreBuilder.from(fetcher = Fetcher.of {
            service.getCountries().toDomain()
        }, sourceOfTruth = sourceOfTruth).build()
```

Error: 

java.lang.NoSuchMethodError: No static method getHours(I)D in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/com.emob-RAUjeqC79K-2HHyHSkrcZg==/base.apk!classes29.dex)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:15)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:91)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:76)

How can I overcome this?

Thanks

**Comment by digitalbuddha** [comment]
#265 should fix it, I'll try to release in AM, we had atravis issue to deal with

**Comment by user-fal** [comment]
@digitalbuddha  thanks. 

By the way, I have the same kind of error when using Memory Policy

Complement of code:

 val memoryPolicy = MemoryPolicy.builder<String, List<CountryBean>>().setExpireAfterWrite(90.days).build()

Error:

java.lang.NoSuchMethodError: No static method toDuration(DLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/com.emob-NxlO4Hq0cK34IJJXwIX_yQ==/base.apk!classes29.dex)
        at com.dropbox.android.external.store4.MemoryPolicy.<clinit>(MemoryPolicy.kt:116)
        at com.emob.framework.room.persistence.HCCStorage.loadCountries(HCCStorage.kt:37)
        at com.emob.usecase.houses_countries_cities.LoadCountries.invoke(LoadCountries.kt:14)

If you can fix it also in the new release, that will be great ;).

Thanks

**Comment by digitalbuddha** [comment]
New version is out https://search.maven.org/artifact/com.dropbox.mobile.store/store4/4.0.1/jar

**Comment by user-fal** [comment]
@digitalbuddha thanks but in my side, app stills crash. 

java.lang.NoSuchMethodError: No static method toDuration(ILjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/com.emob-W9JUQFTc0-_KesZnIOaYNA==/base.apk!classes29.dex)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:16)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:91)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:76)
