### ISSUE TITLE
Support inline classes as Store Key

### ISSUE THREAD

**Issue by DanielAsher** [dropbox/Store#77]
I use `inline class` to strongly-type string classes and would like to use these as `Key` and `Output` in the `Store`. When implementing a persister, this lead to an exception e.g:

`Exception in thread "DefaultDispatcher-worker-2 @coroutine#7" java.lang.ClassCastException: com.example.app.KeyPath cannot be cast to java.lang.String`

I'm not sure if this is a user error, an unsupported use-case or a bug.

Here is a small reproduction:
```
package com.example.app

import com.dropbox.android.external.store4.MemoryPolicy
import com.dropbox.android.external.store4.StoreBuilder
import com.dropbox.android.external.store4.get
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.FlowPreview
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Test

inline class KeyPath(val string: String)
inline class LocalFilePath(val string: String)

@ExperimentalCoroutinesApi
@FlowPreview
class MediaStoreTest {
    @Test
    fun testStoreInlineClassKey() {
        val localDirectory = "/data/user/0/com.example.app/cache/"
        val store = StoreBuilder.from { keyPath: KeyPath ->
            flow { emit(LocalFilePath("$localDirectory${keyPath.string}")) }
        }.persister(reader = {
            val local: LocalFilePath? = null
            flow { emit(local) }
        }, writer = { key, output ->
        }, delete = {
        })
            .build()
        runBlocking {
            store.get(KeyPath("hello.txt"))
        }
    }
}
```

Stack trace:

```
Exception in thread "DefaultDispatcher-worker-2 @coroutine#7" java.lang.ClassCastException: com.example.app.KeyPath cannot be cast to java.lang.String
	at com.example.app.MediaStoreTest$testStoreInlineClassKey$store$3.invoke(MediaStoreTest.kt)
	at com.dropbox.android.external.store4.impl.PersistentSourceOfTruth.write(SourceOfTruth.kt:44)
	at com.dropbox.android.external.store4.impl.SourceOfTruthWithBarrier.write(SourceOfTruthWithBarrier.kt:95)
	at com.dropbox.android.external.store4.impl.FetcherController$fetchers$1$3.invokeSuspend(FetcherController.kt:77)
	at com.dropbox.android.external.store4.impl.FetcherController$fetchers$1$3.invoke(FetcherController.kt)
	at com.dropbox.flow.multicast.ChannelManager$Actor.doDispatchValue(ChannelManager.kt:184)
	at com.dropbox.flow.multicast.ChannelManager$Actor.handle(ChannelManager.kt:118)
	at com.dropbox.flow.multicast.ChannelManager$Actor.handle(ChannelManager.kt:86)
	at com.dropbox.flow.multicast.StoreRealActor$1.invokeSuspend(StoreRealActor.kt:50)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

Thanks!

**Comment by ychescale9** [comment]
Looks like it's a bug in the Kotlin compiler where [inlined type doesn't work with suspend lambda with multiple parameters](https://youtrack.jetbrains.com/issue/KT-32821). In our case it's this lambda here: https://github.com/dropbox/Store/blob/86f7b1b06068a6665895d179b6f4bf8c0f181dc4/store/src/main/java/com/dropbox/android/external/store4/impl/SourceOfTruth.kt#L39

A simple test case:

```kotlin
inline class MyKey(val key: String)
inline class MyValue(val value: String)

class InlineClassTest {

    private val write: suspend (MyKey, MyValue) -> Unit = { key, value ->
        print("$key, $value")
    }

    @Test
    fun test() {
        runBlocking {
            write(MyKey("key"), MyValue("value"))
        }
    }
}
```

Stacktrace:

```
com.example.MyKey cannot be cast to java.lang.String
java.lang.ClassCastException: com.example.MyKey cannot be cast to java.lang.String
	at com.example.InlineClassTest$write$1.invoke(InlineClassTest.kt)
	at com.example.InlineClassTest$test$1.invokeSuspend(InlineClassTest.kt:35)
```

**Comment by digitalbuddha** [comment]
please track on kotlin repo. Closing here
