### ISSUE TITLE
Bug? NonFlow Source of truth does not return network value

### ISSUE THREAD

**Issue by digitalbuddha** [dropbox/Store#81]
I wrote a test using both alpha and snapshot and both fail by not emitting the data. Is there something that needs to be adjusted?  Opening issue for tracking I will continue to look tomorrow:

```
class PadStoreTest {
    private val testScope = TestCoroutineScope()

    lateinit var padStore: Store<String, String>
    @Before
    fun setup() {
        /*
         StoreBuilder
            .fromNonFlow<String, String> {
                apiService.getPadIdAndFileObjIdFromCloudDocId(it).localPadId
            }
            .nonFlowingPersister(
                writer= {key,value->keyValueStore.update(StoreKey.StringValue(key), value)},
                reader = {key-> keyValueStore.getSuspendedString(StoreKey.StringValue(key))})
            .build()
         */
        padStore = PadStoreModule.providePadStore(fakePadApi, fakeSuspendKeyValueStore)
    }

    @Test
    fun `Given a PadStore WHEN data is fetched THEN first load from network AND then load from cache`() {
        testScope.runBlockingTest {
           assertThat(padStore.stream(StoreRequest.fresh("5")))
               .emitsExactly(
                   StoreResponse.Loading(
                       origin = ResponseOrigin.Fetcher
                   ),
                   StoreResponse.Data(
                       value = "55",
                       origin = ResponseOrigin.Fetcher
                   )
               )

        }
    }

}

private val fakePadApi: CloudToPadIDApiService = object : CloudToPadIDApiService {
    override suspend fun getPadIdAndFileObjIdFromCloudDocId(cloudDocId: String): GetCloudDocInfoResponse {
        return GetCloudDocInfoResponse(cloudDocId, cloudDocId + cloudDocId, "")
    }
}

private val fakeSuspendKeyValueStore: SuspendingKeyValueStore = object : SuspendingKeyValueStore {
    val fakeDisk: MutableMap<StoreKey, String> = mutableMapOf(StoreKey.StringValue("5") to "55")

    override suspend fun update(storeKey: StoreKey, value: String) {
        fakeDisk[storeKey] = value
    }

    override suspend fun getSuspendedString(storeKey: StoreKey): String? {
        return fakeDisk[storeKey]
    }
}```


```
Flow didn't exactly emit expected items
missing (1): Data(value=55, origin=Fetcher)
---
expected   : [Loading(origin=Fetcher), Data(value=55, origin=Fetcher)]
but was    : [Loading(origin=Fetcher)]

	at com.dropbox.paper.pifs.PadStoreTest$Given a PadStore WHEN data is fetched THEN first load from network AND then load from cache$1.invokeSuspend(PadStoreTest.kt:39)
	at com.dropbox.paper.pifs.PadStoreTest$Given a PadStore WHEN data is fetched THEN first load from network AND then load from cache$1.invoke(PadStoreTest.kt)
	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch(TestCoroutineDispatcher.kt:50)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:271)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:89)
	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:82)
	at kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:49)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:72)
	at com.dropbox.paper.pifs.PadStoreTest.Given a PadStore WHEN data is fetched THEN first load from network AND then load from cache(PadStoreTest.kt:37)
```

**Comment by digitalbuddha** [comment]
Not a bug, I forgot to pass test scope to store builder. As a result my test finished before data came
