### ISSUE TITLE
cache concurrent modification exception

### ISSUE THREAD

**Issue by yigit** [dropbox/Store#89]
I've noticed this while trying to repro issue #86 .

```
2020-02-03 21:07:37.721 11904-11904/com.dropbox.stor4.bug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dropbox.stor4.bug, PID: 11904
    java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
        at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
        at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:185)
        at com.dropbox.android.external.cache4.RealCache.evictEntries(RealCache.kt:218)
        at com.dropbox.android.external.cache4.RealCache.put(RealCache.kt:147)
        at com.dropbox.android.external.store4.impl.RealStore$stream$2.invokeSuspend(RealStore.kt:114)
        at com.dropbox.android.external.store4.impl.RealStore$stream$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:138)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:33)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:33)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:33)
        at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1.emit(Collect.kt:138)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:33)
        at com.dropbox.flow.multicast.Multicaster$newDownstream$2$invokeSuspend$$inlined$transform$1$1.emit(Collect.kt:138)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAll(Channels.kt:56)
        at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAll$1.invokeSuspend(Unknown Source:10)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

https://github.com/atonamy/store4-issue

To reproduce, checkout the app and hit refresh couple of times and eventually happens. Sorry i know it is not great repro but i'm focusing on the other bug right now so wanted to report this w/o being side-tracked.
.

**Comment by ychescale9** [comment]
Thanks. Will take a look.
